reC4P7CH4/A21-EasyContact

DataBase/Contact.h
DataBase/TierDB.h

	modified:   DataBase/Contact.h

---

Web/index.html
Web/main_page.js
Web/server.js

Demo version with add and show features

GUI - Update Interface

---

Web/main_page.css

MERGE - Local Branch Update

---

DataBase/Contact.h
DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h
DataBase/DATABASE_INCLUDE.h
DataBase/DB_Export.h
DataBase/DB_Import.h
DataBase/DB_Main.cpp
DataBase/EmailReader.h
DataBase/Merge.h
DataBase/Priority.h
DataBase/Weight.h

DataBase - Email Reader

---

DataBase/ContactWithGroup.h
DataBase/DB_Import.h
DataBase/DB_Main.cpp

DataBase - Import

---

DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h
DataBase/DATABASE_INCLUDE.h
DataBase/DB_Main.cpp
DataBase/EmailReader.h
DataBase/Priority.h
DataBase/Weight.h

DataBase - Priority Sort

---

.github/workflows/CodeQL.yml

WORKFLOW - CodeQL (JavaScript)

---

DataBase/DB_Import.h

DataBase - Import UPDATE

---

DataBase/DB_Import.h
DataBase/DB_Main.cpp
DataBase/EmailReader.h
DataBase/Priority.h
DataBase/README.md

DataBase - MultiThreads (FORK --> PTHREAD)

---

.github/workflows/CodeQL.yml

WORKFLOW - CodeQL (CPP)

---

DataBase/ContactWithGroup.h
DataBase/DB_Main.cpp
DataBase/EmailReader.h

DataBase - Priority Sort Trigger

---

DataBase/DB_Main.cpp

HOTFIX - Main Executable

---

DataBase/README.md

HOTFIX - DataBase README

---

DataBase/DB_Import.h
DataBase/DB_Main.cpp

HOTFIX - DataBase Import

---

DataBase/DB_Main.cpp
DataBase/EM_Import.h

DataBase - EM Import

---

DataBase/README.md
INSTALL.md

HOTFIX - README Update

---

DataBase/APIAccess.h
DataBase/Contact.h
DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h
DataBase/DB_Main.cpp
DataBase/apidemo.cpp

HOTFIX - Compare Contact Objects

---

DataBase/Contact.h
DataBase/ContactNOGroup.h
DataBase/DB_Import.h
DataBase/DB_Main.cpp

HOTFIX - Negative Phone Numbers

---

DataBase/Contact.h
DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h
DataBase/DB_Main.cpp
DataBase/EmailReader.h
DataBase/Priority.h

HOTFIX - Update New Email

---

DataBase/Contact.h
DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h
DataBase/Weight.h

HOTFIX - Contacts Automatic Sorting

---

DataBase/ContactNOGroup.h
DataBase/ContactWithGroup.h

HOTFIX - Time Based Sorting DISABLE

---

INSTALL.sh
SECURITY.md

INSTALLER - Ubuntu 20.04 LTS

---

DataBase/ContactWithGroup.h
DataBase/DB_Import.h

HOTFIX - Startup Time
